name: playguide
favicon: null
layout_spectrum: 0.1137376930564642
typography_spectrum: 0.44343123747967184
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.9012902621179819
  lightness: 0.1216820552945137
  saturation: 0.0226872896309942
  rhythmicContrast: 0.8558096780907363
purpose: []
